DROP TABLE IF EXISTS "sun";
DROP TABLE IF EXISTS "humidity";
DROP TABLE IF EXISTS "wind";
DROP TABLE IF EXISTS "device";
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "images";
DROP TABLE IF EXISTS "county";

